### PR TITLE
Removed Console.Writeline to keep terminal neat

### PR DESCRIPTION
**Pull request by Allezk**

### CODE REVIEW

**Comment by aksoftware98** [comment]
Thank you so much for the PR Allezk, I will make sure to publish the new version later on today.

**Comment by Allezk** [comment]
Any ETA when the new version will be up? Great package just a little annoying with the lines in the terminal.  :)

**Comment by aksoftware98** [comment]
Really sorry for being late but with 10 hours it will be online

Thanks a lot

On 13 Nov 2021, at 3:52 pm, Allezk ***@***.***> wrote:

﻿

Any ETA when the new version will be up? Great package just a little annoying with the lines in the terminal. :)

**Comment by aksoftware98** [comment]
Hi 

The package has been published really appreciate your help and sorry for being late. 

Best regards

**Comment by Allezk** [comment]
Hi,

Great thank you. Really appreciate it.

**Pull request merged**
